### ISSUE TITLE
How do you sample into an image? 

### ISSUE THREAD

**Issue by zohairshafi** [hardmaru/cppn-tensorflow#2]
Hello!
I love your work and wanted to try implementing the same in Keras. 
I don't understand how and where in your code you are forward propagating through the network for each pixel position and storing it. 

Could you please help me understand this? 

Thank you!

**Comment by hardmaru** [comment]
Hi!

It's been a while since I looked at this code.

Can you take a look at this Keras implementation and see how they did it?

https://janhuenermann.com/blog/abstract-art-with-ml

**Comment by zohairshafi** [comment]
Hey that really helped! Thank you so much! 
Love your work as well! Its genuinely incredible!
